# Generated by Django 3.0.8 on 2020-07-28 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(db_index=True, max_length=50)),
                ('companyCode', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('contacts', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('workingShedule', models.CharField(max_length=50)),
                ('isActive', models.BooleanField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderCode', models.CharField(max_length=50)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('isPrepayment', models.BooleanField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Type_of_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityName', models.CharField(max_length=50)),
                ('codeOfActivity', models.CharField(max_length=50, unique=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table_of_restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=50)),
                ('table_desc', models.CharField(max_length=1000)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Services_of_institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_description', models.CharField(max_length=1000)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_duration', models.DurationField(max_length=1000)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.DateField()),
                ('commentOfReview', models.CharField(max_length=1000)),
                ('rating', models.CharField(choices=[(1, 'Bad'), (2, 'Not Bad'), (3, 'Medium'), (4, 'Good'), (5, 'Great')], max_length=1)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Company')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Table_of_restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(db_index=True, max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='idOFLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Location'),
        ),
        migrations.AddField(
            model_name='company',
            name='idOfActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersapp.Type_of_activity'),
        ),
    ]
