# Generated by Django 3.0.8 on 2020-07-28 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='countryName',
            field=models.CharField(default='KZ', max_length=50),
        ),
        migrations.AddField(
            model_name='type_of_activity',
            name='categoryCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type_of_activity',
            name='categoryName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
