# Generated by Django 3.0.8 on 2020-07-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_auto_20200728_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_activity',
            name='categoryCode',
            field=models.CharField(max_length=50),
        ),
    ]
