# Generated by Django 3.0.9 on 2020-08-03 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_auto_20200728_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderCode',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersapp.Services_of_institutions'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersapp.Table_of_restaurant'),
        ),
    ]
